services:
  app:
    build: ./backend
    container_name: bizoni-app
    environment:
      - STATIC_PATH=/app/site
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./:/app/site
    restart: unless-stopped
